### PR TITLE
Update makerchip_examples

### PR DESCRIPTION
**Pull request by Alchemist1411**

### CODE REVIEW

**Review by stevehoover — APPROVED** [review]
Thanks. (You can also remove all ";".)

**Comment by Alchemist1411** [comment]
Sir, but removing ';' will terminate the programm someplaces . So , that's
why I left it. Should I
remove all ';' in viz_alpha.

**Comment by stevehoover** [comment]
Inside `\viz_alpha` only, yes. I believe is safe to remove them all.

**Comment by Alchemist1411** [comment]
Ok sir

**Pull request merged**
